server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # 301 redirects for old Wix junk URLs
    rewrite ^/chat$ / permanent;
    rewrite ^/services-1$ / permanent;
    rewrite ^/copy-of-services$ / permanent;
    rewrite ^/about-2$ / permanent;
    rewrite ^/move-out-and-deep-cleaning$ / permanent;
    rewrite ^/standard-cleaning$ / permanent;

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }
    location /robots.txt {
        add_header Content-Type text/plain;
        try_files $uri =404;
    }
    location /sitemap.xml {
        add_header Content-Type application/xml;
        try_files $uri =404;
    }
}
